export const APARTMENT_HOST_BTN = "APARTMENT_HOST_BTN;";
export const HOUSE_HOST_BTN = "HOUSE_HOST_BTN;";
export const SECONDARYUNIT_HOST_BTN = "SECONDARYUNIT_HOST_BTN;";
export const BEDNBREAKFAST_HOST_BTN = "BEDNBREAKFAST_HOST_BTN;";
export const BOUTIQUEHOTEL_HOST_BTN = "BOUTIQUEHOTEL_HOST_BTN;";

export const RENTALUNIT_HOST_BTN = "RENTALUNIT_HOST_BTN;";
export const LOFT_HOST_BTN = "LOFT_HOST_BTN;";
export const CONDOMINIUM_HOST_BTN = "CONDOMINIUM_HOST_BTN;";

export const ANENTIREPLACE_HOST_BTN = "ANENTIREPLACE_HOST_BTN;";
export const APRIVATEROOM_HOST_BTN = "APRIVATEROOM_HOST_BTN;";
export const ASHAREDROOM_HOST_BTN = "ASHAREDROOM_HOST_BTN;";

export const LOCATION_HOST_INPUT = "LOCATION_HOST_INPUT";

export const ADDGUEST_HOST_BTN = "ADDGUEST_HOST_BTN";
export const SUBTRACTGUEST_HOST_BTN = "SUBTRACTGUEST_HOST_BTN";
export const ADDBEDS_HOST_BTN = "ADDBEDS_HOST_BTN";
export const SUBTRACTBEDS_HOST_BTN = "SUBTRACTBEDS_HOST_BTN";
export const ADDBEDSROOMS_HOST_BTN = "ADDBEDSROOMS_HOST_BTN";
export const SUBTRACTBEDSROOMS_HOST_BTN = "SUBTRACTBEDSROOMS_HOST_BTN";
export const ADDBATHROOMS_HOST_BTN = "ADDBATHROOMS_HOST_BTN";
export const SUBTRACTBATHROOMS_HOST_BTN = "SUBTRACTBATHROOMS_HOST_BTN";

export const AMENITIES_FAVORITES_SAFETYITEMS_HOST_INPUT =
  "AMENITIES_FAVORITES_SAFETYITEMS_HOST_INPUT";

export const IMAGE_HOST_INPUT = "IMAGE_HOST_INPUT";

export const LATITUDE_LONGITUDE_HOST_INPUT = "LATITUDE_LONGITUDE_HOST_INPUT";

export const TITLE_DECRIPTION_HOST_INPUT = "TITLE_DECRIPTION_HOST_INPUT";

export const PRICE_HOST_INPUT = "PRICE_HOST_INPUT";
